<?php

namespace AgrikathonBundle\Repository;

/**
 * DescriptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DescriptionRepository extends \Doctrine\ORM\EntityRepository
{
}
